sudo: required
dist: xenial
language: cpp
branches:
  only:
    - master
    - master1.1
    - test

addons:
  apt:
    packages: &common_packages
      - asciidoctor
      - cmake
      - libboost-dev
      - libmpich-dev
      - libexpat1-dev
      - qttools5-dev
      - qttools5-dev-tools
      - qtbase5-dev
      - qtbase5-dev-tools
      - libqt5svg5-dev
      - qtchooser
      - qt5-default

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          packages:
            - *common_packages
            - g++
      env:
        - CXX_COMPILER=g++ C_COMPILER=gcc
        - QT_SELECT=qt5
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - *common_packages
            - g++-6
      env:
        - CXX_COMPILER=g++-6 C_COMPILER=gcc-6
        - QT_SELECT=qt5
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - *common_packages
            - g++-7
      env:
        - CXX_COMPILER=g++-7 C_COMPILER=gcc-7
        - QT_SELECT=qt5
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - *common_packages
            - g++-8
      env:
        - CXX_COMPILER=g++-8 C_COMPILER=gcc-8
        - QT_SELECT=qt5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - *common_packages
            - clang-3.9
      env:
        - CXX_COMPILER=clang++-3.9 C_COMPILER=clang-3.9
        - QT_SELECT=qt5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - *common_packages
            - clang-4.0
      env:
        - CXX_COMPILER=clang++-4.0 C_COMPILER=clang-4.0
        - QT_SELECT=qt5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - *common_packages
            - clang-5.0
      env:
        - CXX_COMPILER=clang++-5.0 C_COMPILER=clang-5.0
        - QT_SELECT=qt5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - *common_packages
            - clang-6.0
      env:
        - CXX_COMPILER=clang++-6.0 C_COMPILER=clang-6.0
        - QT_SELECT=qt5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-7
          packages:
            - *common_packages
            - clang-7
      env:
        - CXX_COMPILER=clang++-7 C_COMPILER=clang-7
        - QT_SELECT=qt5

before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$CXX_COMPILER -DCMAKE_C_COMPILER=$C_COMPILER -DCMAKE_BUILD_TYPE=RelWithDebInfo -DWITH_GVLE=ON -DWITH_CVLE=ON -DWITH_MVLE=ON ..
script:
  - make
  - sudo make install
  - ctest -V

notifications:
  irc:
    channels:
      - "chat.freenode.net#vle"
    template:
      - "%{repository} (%{commit}) : %{message} %{foo} "
      - "Build details: %{build_url}"
