sudo: required
dist: trusty
language: cpp
branches:
  only:
    - master
    - master1.1
    - test

addons:
  apt:
    packages: &common_packages
      - cmake
      - libboost-dev
      - libmpich-dev
      - libexpat1-dev
      - qttools5-dev
      - qttools5-dev-tools
      - qtbase5-dev
      - qtbase5-dev-tools
      - libqt5svg5-dev
      - qtchooser
      - qt5-default

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - *common_packages
            - g++-4.9
      env:
        - CXX_COMPILER=g++-4.9 C_COMPILER=gcc-4.9
        - QT_SELECT=qt5
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - *common_packages
            - g++-5
      env:
        - CXX_COMPILER=g++-5 C_COMPILER=gcc-5
        - QT_SELECT=qt5
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - *common_packages
            - g++-6
      env:
        - CXX_COMPILER=g++-6 C_COMPILER=gcc-6
        - QT_SELECT=qt5
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - *common_packages
            - g++-7
      env:
        - CXX_COMPILER=g++-7 C_COMPILER=gcc-7
        - QT_SELECT=qt5
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - *common_packages
            - g++-8
      env:
        - CXX_COMPILER=g++-8 C_COMPILER=gcc-8
        - QT_SELECT=qt5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - *common_packages
            - clang-3.6
      env:
        - CXX_COMPILER=clang++-3.6 C_COMPILER=clang-3.6
        - QT_SELECT=qt5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - *common_packages
            - clang-3.7
      env:
        - CXX_COMPILER=clang++-3.7 C_COMPILER=clang-3.7
        - QT_SELECT=qt5

before_script:
  - gem install asciidoctor
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$CXX_COMPILER -DCMAKE_C_COMPILER=$C_COMPILER -DCMAKE_BUILD_TYPE=RelWithDebInfo -DWITH_GVLE=ON -DWITH_CVLE=ON -DWITH_MVLE=ON ..
script:
  - make
  - sudo make install
  - ctest -V

notifications:
  irc:
    channels:
      - "chat.freenode.net#vle"
    template:
      - "%{repository} (%{commit}) : %{message} %{foo} "
      - "Build details: %{build_url}"
