/* config.h. Generated by cmake from config.h.cmake */

#define HAVE_GCC_ABI_DEMANGLE ${HAVE_GCC_ABI_DEMANGLE}
#define HAVE_EXECINFO_H ${HAVE_EXECINFO_H}
#define HAVE_SIGNAL_H ${HAVE_SIGNAL_H}
#define VERSION "${VLE_PACKAGE_VERSION}"
