.TH "CVLE" "1"

.SH "NAME"
cvle \(em The MPI experimental frames executor for VLE framework

.SH "SYNOPSIS"
.PP
\fBcvle\fR
[\fB-h\fP, \fB\-\-help\fP]
[\fB\-\-timeout \fIduration\fP\fR]
[\fB\-P\fP, \fB\-\-package \fIpackage_name\fP\fR]
[\fB\-i\fP, \fB\-\-input-file \fIinput_file.csv\fP\fR]
[\fB\-o\fP, \fB\-\-output-file \fIoutput_file.csv\fP\fR]
[\fB\-t\fP, \fB\-\-template \fItemplate.csv\fP\fR]
[\fB\-b\fP, \fB\-\-block-size \fIsize\fP\fR]
[\fB\-\-warnings\fP\fR]
[\fB\-\-version\fP]
\fB\fIvpz file\fP

.SH "DESCRIPTION"
.PP
This manual page documents briefly the \fBcvle\fR command.
.PP
\fBCVLE\fR is a part of a multi-modelling and simulation framework
call \fBVLE\fR. It addresses the reliability issue using recent
developments in the theory of Modelling and Simulation proposed by
Zeigler and open sources software.
.PP
\fBCVLE\fR is a program to execute a set of simulation on classical
cluster system. CVLE uses the \fBMPI\fR (Message Parsing Interface).
.PP
\fBCVLE\fR treats huge simulation plan. \fBCVLE\fR does not use the
classical VLE's manager to build the experimental frames. It reads a
Comma-Separated Value (CSV) where columns are conditions, lines are
instances of the experimental frame. The first line (header) of the
input file defines the conditions. If a column does not exist in the
VPZ file, it is simply added to he output file (e.g. to store
simulation id).
.PP
The column header is a list of string of the following format:
.IP "\fBcondition_name.port_name([.set_index]|[.map_key])*\fP"
Represents an access to a value of the specified condition,
port. Values can be bool, integer, double or string.

.IP "\fBundefined string\fP"
If the string is unknown, the string is reported into the output
file. This feature is useful to assign index or a list of identifier
for each simulation.

.PP
For example, the column name "cond.x.2.default" tries to access the
map's key 'default' in the 3rd element (start from 0) of the set of
the condition

.SH "OPTIONS"
.PP
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`\-'). A summary of options is
included below.

.IP "\fB-h\fP, \fB\-\-help\fP" 10
Show summary of options.

.IP "\fB-P\fP, \fB\-\-timeout\fI duration\fR\fP"
Limit the simulation duration with a timeout in miliseconds (integer).

$VLE_HOME directory.

.IP "\fB-P\fP, \fB\-\-package\fI packagename\fR\fP"
Selects the VLE package where search experimental frame from the
$VLE_HOME directory.

.IP "\fB-V\fP, \fB\-\-vpz\fI vpzfile\fR\fP"
Selects the VPZ file from package.

.IP "\fB-i \fI file\fR\fp, \fB\-\-input-file \fI file\fR\fP" 10
The input file to initialize simulation. Each column is a condition
for the simulation. The first line describes condition's name in VPZ
file. Without this parameter, \fBCVLE\fR reads the standard input.

.IP "\fB-o \fI file\fR\fp, \fB\-\-output-file \fI file\fR\fP" 10
The output file generated by simulations. Without this parameter,
\fBCVLE\fR writes results into the standard output.

.IP "\fB-t \fI file\fR\fp, \fB\-\-template \fI file\fR\fP" 10
Generate an input csv file from conditions availables in the VPZ file.

.IP "\fB\-b \fI size\fR\fP, \fB\-\-block-size \fI size\fR\fP" 10
Defines the number of line to be read by the master and send per each worker
(each MPI process).

.IP "\fB\-\-warnings\fI\fR\fP"
Shows warnings throw by simulator on error standard output. Default is true.

.SH "EXAMPLES"
.PP
Run cvle on 32 process, for the experimental frame `firemanqss-exp.vpz' of the
package `firemanqss':
.PP
$ mpirun -np 32 cvle -i input.file -o output.file -P firemanqss firemanqss-exp.vpz

.PP
Run cvle on 2048 processor from a specified machine file, for the experimental
frame `firemanqss-exp.vpz' of the package `firemanqss' and reads the CSV from
standard input.
.PP
$ mpirun -np 2048 --machinefile file.txt cvle -o output.file -P vle.examples unittest.vpz

.SH "ENVIRONMENTS"
.IP VLE_HOME
A path where you push models packages (ie. simulators, streams and
modelling plugins, vpz files, data, and the outputs of simulation)

.SH "SEE ALSO"
.PP
vle (1), mvle (1) and gvle (1).

.SH "AUTHOR"
.PP
Gauthier Quesnel \fBgauthier.quesnel@inra.fr\fP
.PP
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or (at
your option) any later version.

.SH "COPYRIGHT"
.PP
Copyright (c) 2015-2017 INRA http://www.inra.fr
