.TH "MVLE" "1"

.SH "NAME"
mvle \(em The MPI experimental frames executor for VLE framework

.SH "SYNOPSIS"
.PP
\fBmvle\fR
[\fB-h\fP, \fB\-\-help\fP]
[\fB\-\-timeout \fIduration\fP\fR]
[\fB\-P\fP, \fB\-\-package \fIpackage_name\fP\fR]
[\fB\-v\fP]
[\fB\-\-version\fP]
\fB\fIvpz files\fP...

.SH "DESCRIPTION"
.PP
This manual page documents briefly the \fBmvle\fR command.
.PP
\fBMVLE\fR is a part of a multi-modelling and simulation framework call
\fBVLE\fR. It addresses the reliability issue using recent developments in the
theory of Modelling and Simulation proposed by Zeigler and open sources
software. \fBVLE\fR is composed of five applications: \fIVLE\fR the simulator,
\fIGVLE\fR the modelling tool.
.PP
\fBMVLE\fR is a program to execute experimental frame on classical cluster
system: \fBMPI\fR (Message Parsing Interface).

.SH "OPTIONS"
.PP
These programs follow the usual GNU command line syntax, with long options
starting with two dashes (`\-'). A summary of options is included below.

.IP "\fB-h\fP, \fB\-\-help\fP" 10
Show summary of options.

.IP "\fB-v\fp, \fB\-\-version\fP" 10
Show version of program.

.IP "\fB-P\fP, \fB\-\-timeout\fI duration\fR\fP"
Limit the simulation duration with a timeout in miliseconds (integer).

.IP "\fB-P\fP, \fB\-\-package\fI packagename\fR\fP"
Selects the VLE package where search experimental frame from the $VLE_HOME
directory.

.SH "EXAMPLES"
.PP
Run mvle on 32 process, for the experimental frame `firemanqss-exp.vpz' of the
package `firemanqss':
.PP
$ mpirun -np 32 mvle -P firemanqss firemanqss-exp.vpz

.PP
Run mvle on 2048 processor from a specified machine file, for the experimental
frame `firemanqss-exp.vpz' of the package `firemanqss':
.PP
$ mpirun -np 2048 --machinefile file.txt mvle -P vle.examples unittest.vpz

.SH "ENVIRONMENTS"
.IP VLE_HOME
A path where you push models packages (ie. simulators, streams and modelling
plugins,  vpz files, data, and the outputs of simulaton)

.SH "SEE ALSO"
.PP
vle (1), cvle (1) and gvle (1).

.SH "AUTHOR"
.PP
Gauthier Quesnel \fBgauthier.quesnel@inra.fr\fP
.PP
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

.SH "COPYRIGHT"
.PP
Copyright (c) 2003-2017 Gauthier Quesnel <gauthier.quesnel@inra.fr>
.PP
Copyright (c) 2003-2017 ULCO http://www.univ-littoral.fr
.PP
Copyright (c) 2007-2017 INRA http://www.inra.fr
