.TH "VLE" "1"

.SH "NAME"
vle \(em The simulator for VLE framework

.SH "SYNOPSIS"
.PP
\fBvle\fR
[\fB\-h\fP,\fB\-\-help\fP]
[\fB-v\fP,\fB\-\-version\fP]
[\fB\-\-infos\fP]
[\fB\-\-timeout \fIduration\fP\fR]
[\fB\-P \fIname\fP,\fB\-\-package=\fIname\fP
\fBcreate\fP,\fBconfigure\fP,\fBbuild\fP,\fBtest\fP,\fBinstall\fP,\fBclean\fP,
\fBrclean\fP,\fBpackage\fP,\fBall\fP,\fBdepends\fP,\fBlist\fP,\fB\fIVPZ\fP files...\fR]
[\fB\-R,\-\-remote \fBupdate\fP,\fBinstall\fP,\fBsearch\fP,\fBshow\fI remote_package]
[\fB-o \fIint\fP,\fB\-\-process=\fIint\fP\fR]
[\fB-V \fIint\fP,\fB\-\-verbose=\fIint\fP\fR]
[\fB-m\fP]
[\fB\fIVPZ\fP files...\fR]

.SH "DESCRIPTION"
.PP
This manual page documents briefly the \fBVLE\fR command.
.PP
\fBVLE\fR is a part of a multi-modelling and simulation framework call
\fBVLE\fR. It addresses the reliability issue using recent developments in the
theory of Modelling and Simulation proposed by Zeigler and open sources
software. \fBVLE\fR is composed of 3 applications: \fIVLE\fR the simulator,
\fIGVLE\fR the modelling tool, \fIMVLE\fR the MPI simulation manager
.PP
\fBVLE\fR is a program that simulate the VPZ files. \fBVLE\fR use two modes:
\fBmanager\fP or just to run simulation. \fBManager\fP run
experimentals frames to build VPZ instances files. \fBJustRun\fP is the mode to run a VPZ directly.

.SH "OPTIONS"
.PP
These programs follow the usual GNU command line syntax, with long options
starting with two dashes (`\-'). A summary of options is included below.

.IP "\fB-h\fP, \fB\-\-help\fP" 10
Show summary of options.

.IP "\fB-v\fP, \fB\-\-version\fP" 10
Show version of program.

.IP "\fB\-\-info\fP" 10
Show somes informations for vle framework.

.IP "\fB-P\fP, \fB\-\-timeout\fI duration\fR\fP"
Limit the simulation duration with a timeout in miliseconds (integer).

.IP "\fB-V\fI int\fR\fP, \fB\-\-verbose\fI int \fR\fP"
Set the verbosity of this application. Default is \fI0\fR, only problem in VLE,
\fI1\fR trace users' models problem, \fI2\fR trace extension process and
\fI3\fR trace all DEVS API. Logs are stored in $VLE_HOME/vle.log.

.IP "\fB\-P \fIname\fP, \fB\-\-package \fIname\fP" 10
Select a package (in $VLE_HOME/pkgs). After this command you can use:
\fIcreate\fR, \fIconfigure\fR, \fIbuild\fR, \fItest\fR, \fIinstall\fR, \fIclean\fR,
\fIrclean\fR, \fIpackage\fR, \fIall\fR, \fIdepends\fR, \fIlist\fR and/or
a list of VPZ files
        vle --package foo create: build new foo package
        vle --package foo configure: configure the foo package
        vle --package foo build: build the foo package
        vle --package foo test: start a unit test campaign
        vle --package foo install: install libs
        vle --package foo clean: clean up the buildvle directory
        vle --package foo rclean: remove binary directories
        vle --package foo package: build package source and binary
        vle --package foo all: build all depends of foo package
        vle --package foo depends: list depends of foo package
        vle --package foo list: list vpz and library package

.IP "\fB\-R, \fB\-\-remote"
Update the database, install a source or a binary remote package, search
package with regular expression of show information of a remote package.
        vle --remote update
        vle --remote install remote_package
        vle --remote source remote_package
        vle --remote search 'regular expression'
        vle --remote show remote_package

.IP "\fB-m\fP" 10
Run \fBVLE\fP in
\fBmanager\fP mode.

.IP "\fB-o\fI int\fR\fP, \fB\-\-process\fI int \fR\fP
Number of process available for this computer. Default is only one. This option
is only available for the \fBsimulator\fP application.

.SH "EXAMPLES"
.PP
Create a new package firemaqss:
.PP
$ vle -P firemanqss create

.PP
Configure and build the source and list all library and vpz existing in this
package:
.PP
$ vle -P firemanqss configure build list

.PP
Run the simulator in just mode in for the package firemanqss for a vpz file:
.PP
$ vle -P firemanqss file.vpz

.PP
Run the simulator with four threads for multiple vpz files:
.PP
$ vle -o 4 -P firemanqss file.vpz file2.vpz file3.vpz file4.vpz file5.vpz file6.vpz

.PP
Run the manager to build experimental frames on localhost with one thread in
the package firemanqss:
.PP
$ vle --package firemanqss -m file.vpz

.PP
Run the manager to build experimental frames on localhost with four threads:
.PP
$ vle -o 4 -m -P firemanqss file.vpz

.SH "ENVIRONMENTS"
.IP VLE_HOME
A path where you push models packages (ie. simulators, vpz files, data, etc.),
and the outputs, streams and conditions plug-ins.

.SH "FILES"
.IP $VLE_HOME/vle.conf 10
VLE and GVLE configuration file.

.IP $VLE_HOME/vle.log 10
All log of the last call of VLE.

.IP $VLE_HOME/gvle.log 10
All log of the last call of GVLE.

.SH "SEE ALSO"
.PP
cvle (1), mvle (1) and gvle (1).

.SH "AUTHOR"
.PP
Gauthier Quesnel \fBgauthier.quesnel@inra.fr\fP
.PP
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

.SH "COPYRIGHT"
.PP
Copyright (c) 2003-2017 Gauthier Quesnel <gauthier.quesnel@inra.fr>
.PP
Copyright (c) 2003-2017 ULCO http://www.univ-littoral.fr
.PP
Copyright (c) 2007-2017 INRA http://www.inra.fr
