.TH "VLE" "1" 

.SH "NAME" 
VLE \(em The simulator for VLE framework 

.SH "SYNOPSIS" 
.PP 
\fBvle\fR
[\fB-?\fP]
[\fB\-\-help\fP]
[\fB\-\-help-all\fP]
[\fB\-\-help-mangroup\fP]
[\fB\-\-help-simgroup\fP]
[\fB\-\-help-globalgroup\fP]
[\fB-d\fP]
[\fB\-\-daemon\fP]
[\fB\-\-allinlocal\fP]
[\fB-o \fIint\fP\fR]
[\fB\-\-process \fIint\fP\fR]
[\fB-i\fP]
[\fB\-\-infos\fP]
[\fB\-\-version\fP]
[\fB-v\fP]
[\fB\-\-verbose \fIint\fP\fR]
[\fB-m\fP]
[\fB-s\fP]
[\fB-j\fP]
[\fB-p \fIint\fP\fR]
[\fB\fIVPZ\fP or \fIVPZi\fP files...\fR]

.SH "DESCRIPTION" 
.PP 
This manual page documents briefly the \fBVLE\fR command. 
.PP
\fBVLE\fR is a part of a multi-modelling and simulation framework call
\fBVLE\fR. It addresses the reliability issue using recent developments in the
theory of Modelling and Simulation proposed by Zeigler and open sources
software. \fBVLE\fR is composed of four applications: \fIVLE\fR the simulator,
\fIGVLE\fR the modelling tool, \fIAVLE\fR the analysis tools post-simulation
and \fIEOV\fR a real time application to make observation.
.PP 
\fBVLE\fR is a program that simulate the VPZ files. \fBVLE\fR use three modes:
\fBmanager\fP, \fBsimulator\fP or just to run simulation. \fBManager\fP run
experimentals frames to build VPZ instances files. \fBSimulator\fP is use to
run VPZ or VPZi simulations in parallel. \fBJustRun\fP is the mode to run a VPZ
or VPZi directly. This command is used by \fBSimulator\fP.

.SH "OPTIONS" 
.PP 
These programs follow the usual GNU command line syntax, with long options
starting with two dashes (`\-'). A summary of options is included below. 

.IP "\fB-?\fP, \fB\-\-help\fP" 10 
Show summary of options. 

.IP "\fB-i\fP, \fB\-\-info\fP" 10 
Show somes informations for vle framework. 

.IP "\fB\-\-version\fP" 10 
Show version of program. 

.IP "\fB-m\fP" 10 
Run \fBVLE\fP in 
\fBmanager\fP mode. 

.IP "\fB-s\fP" 10 
Run \fBVLE\fP in 
\fBsimulator\fP mode. 

.IP "\fB-j\fP" 10 
Run \fBVLE\fP directly on all specified files (default mode).

.IP "\fB-v\fI int\fR\fP, \fB\-\-verbose\fI int \fR\fP"
Set the verbosity of application. Default is \fI0\fR, no trace and no long
exception. \fI1\fR for small simulation trace and long exception. \fI2\fR for
long simulation trace. 3 for all simulation trace. 

.IP "\fB-d\fP, \fB\-\-daemon\fP
Run the vle program in daemon mode. This option is only available for the
\fBManager\fP application. This mode just \fBfork\fP the program to attach ppid
to init process. 

.IP "\fB-l\fP, \fB\-\-allinlocal\fP"
Run all instances of the experimental frame on the same computer. This option
is only available for the \fBManager\fP application. 

.IP "\fB-o\fI int\fR\fP, \fB\-\-process\fI int \fR\fP
Number of process available for this computer. Default is only one. This option
is only available for the \fBsimulator\fP application. 

.IP "\fB-p\fI int\fR\fP, \fB\-\-port\fI int \fR\fP
Define the listening port for vle application. Default is 8888. This option is
only available for the mode \fBManager\fP and \fBSimulator\fP. 

.SH "SEE ALSO" 
.PP 
gvle (1), eov (1), avle (1). 

.SH "AUTHOR" 
.PP 
Gauthier Quesnel \fBquesnel@lil.univ-littoral.fr\fP
.PP
Permission is granted to copy, distribute and/or modify this document under the
terms of the GNU General Public License, Version 2 any later version published
by the Free Software Foundation. 

.SH "COPYRIGHT" 
.PP 
Copyright (c) 2003, 2004, 2005, 2006 VLE devlopment team of Universite du
Littoral Cote d'Opale \(em Calais \(em France
