.TH "GVLE" "1"

.SH "NAME"
GVLE \(em The graphical modeling tool for VLE framework

.SH "SYNOPSIS"
.PP
\fBgvle\fR
[\fB\-\-help\fP]
[\fB\-\-infos\fP]
[\fB\-\-version\fP]

.SH "DESCRIPTION"
.PP
This manual page documents briefly the \fBVLE\fR command.
.PP
\fBGVLE\fR is a part of a multi-modelling and simulation framework call
\fBVLE\fR. It addresses the reliability issue using recent developments in the
theory of Modelling and Simulation proposed by Zeigler and open sources
software. \fBVLE\fR is composed of four applications: \fIVLE\fR the simulator,
\fIGVLE\fR the modelling tool, \fIAVLE\fR the analysis tools post-simulation.
.PP
\fBGVLE\fR is a graphical tool to build VPZ files.

.SH "OPTIONS"
.PP
These programs follow the usual GNU command line syntax, with long options
starting with two dashes (`\-'). A summary of options is included below.

.IP "\fB\-\-help\fP" 10
Show summary of options.

.IP "\fB\-\-info\fP" 10
Show somes informations for vle framework.

.IP "\fB\-\-version\fP" 10
Show version of program.

.SH "ENVIRONMENTS"
.IP VLE_HOME
A path where you push models packages (ie. simulators, vpz files, data, etc.),
and the outputs, streams and conditions plug-ins.

.SH "SEE ALSO"
.PP
vle (1) and mvle (1).

.SH "AUTHOR"
.PP
Gauthier Quesnel \fBquesnel@users.sourceforge.net\fP
.PP
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

.SH "COPYRIGHT"
.PP
Copyright (c) 2003-2014 Gauthier Quesnel <quesnel@users.sourceforge.net>
.PP
Copyright (c) 2003-2014 ULCO http://www.univ-littoral.fr
.PP
Copyright (c) 2007-2014 INRA http://www.inra.fr
